name: Build Mod Project

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Fix gradlew line endings
        run: sed -i 's/\r$//' gradlew

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Gradle build
        run: ./gradlew build

      - name: Upload Mod jar
        uses: actions/upload-artifact@v4
        with:
          name: mod-Jar-Package-Zip
          path: build/libs/*.jar